name: Do update

on:
  schedule:
    - cron: '21 0 * * fri'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.2
      with:
        submodules: true
    - uses: actions/setup-python@v4.2.0
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install
    - name: Run
      run: |
        pipenv run python main.py
    - name: Push to srn
      run: |
        eval $(ssh-agent)
        ssh-add - <<< "${{ secrets.SSH_DEPLOY_KEY }}"
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        BRANCH_NAME="wiki-data"
        mkdir -p wiki-data
        cd wiki-data
        git init
        git remote add upstream https://github.com/iBelg/osrs-dps-calc.git
        git remote add origin git@github.com:iBelg/osrs-dps-calc.git
        git fetch upstream
        git checkout -b "$BRANCH_NAME"
        cp ../stats{,.ids.min}.json .
        cp ../npcs{,.min}.json .
        git add stats{,.ids.min}.json
        git add npcs{,.min}.json
        git -c user.name="iBelg" -c user.email="4256757+iBelg@users.noreply.github.com" commit -m "Update wiki data"
        git push -u origin "$BRANCH_NAME" -f
