name: Do update

on:
  schedule:
    - cron: '21 0 * * fri'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install
    - name: Run
      run: |
        pipenv run python main.py
